name: Build master

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - id: var
      name: Setup variables
      run: echo ::set-output name=commit_hash::${GITHUB_SHA:0:7}
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Use gradle cache for faster builds
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
    - name: Validate AW
      run: ./gradlew validateAccessWidener
    - name: Generate assets
      run: ./gradlew runData
    - name: Build with Gradle
      run: ./gradlew build
      env:
        MI_VERSION: git-${{ steps.var.outputs.commit_hash }}
    - name: Autotest Server
      run: |
        rm -rf run || echo "no run directory to remove"
        mkdir run
        echo eula=true >> run/eula.txt
        ./gradlew runAutoTestServer --stacktrace
        ! grep -q FATAL run/logs/latest.log
        ! grep -q JsonSyntaxException run/logs/latest.log
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: modern-industrialization ${{ steps.var.outputs.commit_hash }}
        path: build/libs
